# Generated by Django 5.2.4 on 2025-08-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this ROM', max_length=200)),
                ('game_type', models.CharField(default='pokemon_red', help_text='Game type identifier', max_length=100)),
                ('rom_path', models.CharField(help_text='Path to ROM file', max_length=500)),
                ('mgba_path', models.CharField(blank=True, help_text='Path to mGBA executable (optional)', max_length=500)),
                ('script_path', models.CharField(blank=True, help_text='Path to Lua script (optional)', max_length=500)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default ROM')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Game-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_used', '-created_at'],
            },
        ),
    ]
