# Generated by Django 5.2.4 on 2025-08-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_configuration'),
    ]

    operations = [
    ]
