# Generated by Django 5.2.4 on 2025-08-10 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20250810_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='romconfiguration',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='romconfiguration',
            name='mgba_path',
        ),
        migrations.RemoveField(
            model_name='romconfiguration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='romconfiguration',
            name='rom_path',
        ),
        migrations.RemoveField(
            model_name='romconfiguration',
            name='script_path',
        ),
        migrations.AddField(
            model_name='romconfiguration',
            name='display_name',
            field=models.CharField(default='Unknown ROM', help_text='Auto-generated from ROM filename', max_length=200),
        ),
        migrations.AlterField(
            model_name='romconfiguration',
            name='game_type',
            field=models.CharField(default='unknown_gba', help_text='Auto-detected from ROM filename', max_length=100),
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(help_text='SHA-256 hash for deduplication', max_length=64, unique=True)),
                ('original_name', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_type', models.CharField(help_text='File type: rom, executable, script', max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('stored_path', models.CharField(help_text='Path where file is stored', max_length=500)),
                ('reference_count', models.IntegerField(default=0, help_text='Number of configurations using this file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['file_hash'], name='dashboard_m_file_ha_a878b6_idx'), models.Index(fields=['file_type'], name='dashboard_m_file_ty_b85b00_idx')],
            },
        ),
        migrations.AddField(
            model_name='romconfiguration',
            name='mgba_file',
            field=models.ForeignKey(blank=True, help_text='Reference to mGBA executable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgba_configs', to='dashboard.managedfile'),
        ),
        migrations.AddField(
            model_name='romconfiguration',
            name='rom_file',
            field=models.ForeignKey(blank=True, help_text='Reference to ROM file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rom_configs', to='dashboard.managedfile'),
        ),
        migrations.AddField(
            model_name='romconfiguration',
            name='script_file',
            field=models.ForeignKey(blank=True, help_text='Reference to Lua script', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_configs', to='dashboard.managedfile'),
        ),
    ]
