# Generated by Django 5.2.4 on 2025-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_romconfiguration_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mgba_path',
            field=models.CharField(blank=True, default='', help_text='Path to mGBA executable', max_length=500),
        ),
        migrations.AddField(
            model_name='configuration',
            name='rom_display_name',
            field=models.CharField(blank=True, default='', help_text='Display name for ROM', max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='rom_path',
            field=models.CharField(blank=True, default='', help_text='Path to ROM file', max_length=500),
        ),
    ]
