# Generated by Django 5.2.4 on 2025-08-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_game_detection_fields'),
        ('dashboard', '0006_configuration_mgba_path_and_more'),
    ]

    operations = [
    ]
