# Generated by Django 5.2.4 on 2025-09-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20250817_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='memory_config',
            field=models.JSONField(default=dict, help_text='Memory system configuration'),
        ),
    ]
